### ISSUE TITLE
Missing OLEDFrame.h & OLEDOverlay.h

### ISSUE THREAD

**Issue by mhaack** [euphi/HomieNodeCollection#1]
Hi,

first, nice collection of Homie nodes and tools, thanks.

I tired to use the RBG node in one of my own homie projects, but that seams to relay on some classed I can not found.
The include of 
#include <OLEDFrame.h>
#include <OLEDOverlay.h>
can not be resolved. 

Any hint where I can find them. Thx.

**Comment by euphi** [comment]
Thanks for the question. It seems I forgot to add them to the repository. I will add them, when I'm back at home.

**Comment by euphi** [comment]
I added the necessary files to the repository.
